### ISSUE TITLE
Complete User Class (see comment attached to task)

### ISSUE THREAD

**Issue by dw42CSCE** [dw42CSCE/bigsneezeLLA#36]

**Comment by kylehix10** [comment]
Completed most. Please review my work. Methods that deal with the course hashmap are unfinished

**Comment by 28Karter** [comment]
I'm not sure why it was changed on the UML as well, but why is there a _**PUBLIC**_ method for _**getPassword**_ rather than just using the public boolean _**isMatch**_ that returns if the user login data is equal to the inputted data.

Also createUUID is never called on new user creation

Otherwise, everything looks good
